### ISSUE TITLE
Milestone 1: set up your Kanban board

### ISSUE THREAD

**Issue by jicamargo** [lincoln1883/Appointment-capstone-backend#21]
# Milestone 1: set up your Kanban board

## Team members (5):

1. - @Cosmosha 
2. - @ibugithub 
3. - @lincoln1883 
4. - @MoyasiGinko 
5. - @jicamargo 

-------------
Hello team,

We are excited to present our Kanban board for the Appointment App Capstone Project. We have successfully set up the Kanban board to manage our project tasks, and we believe it's ready for your review and approval.

**Kanban Board Links (Backend and Frontend)**: 
🌐 https://github.com/lincoln1883/Appointment-capstone-backend/projects/1
🖥️ https://github.com/lincoln1883/Appointment-capstone-frontend/projects/1

**Objective**:
Our Kanban board will serve as the primary project management tool for the Appointment App development. It helps us to visualize and manage our tasks efficiently, ensuring that we stay organized and meet project milestones.

**Request for Review**:
We kindly request the project stakeholders and team leads to review the Kanban board for any feedback or suggestions. Your input is essential in ensuring that our project management approach is aligned with our goals and expectations.

Thank you! 👍🏽

**Comment by Meltrust** [comment]
Hi @jicamargo,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, pointed and have descriptionsx✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
